---
{{ readFile "../releases.yaml" }}

bases:
  - ../environments.yaml
  - ../repositories.yaml

releases:
  - <<: *ghost
    installed: true
    name: ghost-application
    namespace: ghost-application
    createNamespace: true