name: Create Cluster

on: push

jobs:
 create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind-kind
      - name: get configs
        run: |
          kubectl config get-contexts
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.2.0
      - name: Test
        run: |
          helmfile -e cluster_test diff
